name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug: List directory structure to verify paths
      - name: List directory structure
        run: |
          pwd
          ls -R # Recursively list all directories and files

      # Set execute permission for mvnw
      - name: Set execute permission for mvnw
        run: |
          chmod +x ./consumer/mvnw
          chmod +x ./producer/mvnw

      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build and package consumer app
      - name: Build and package consumer app
        working-directory: ./consumer
        run: |
          ./mvnw clean package -DskipTests

      # Build Docker image for consumer app
      - name: Build Docker image for consumer app
        run: |
          docker build -t ghcr.io/pravesh-77/consumer-app:latest ./consumer
          echo "${{ secrets.KAFKA_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/pravesh-77/consumer-app:latest

      # Build and package producer app
      - name: Build and package producer app
        working-directory: ./producer
        run: |
          ./mvnw clean package -DskipTests

      # Build Docker image for producer app
      - name: Build Docker image for producer app
        run: |
          docker build -t ghcr.io/pravesh-77/producer-app:latest ./producer
          echo "${{ secrets.KAFKA_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/pravesh-77/producer-app:latest
