name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug: List the directory structure to ensure correct paths
      - name: List directory structure
        run: |
          pwd
          ls -R # Recursively list all directories and files

      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build and package consumer app
      - name: Build and package consumer app
        working-directory: ./assesment/consumer  # Update the path based on the actual repo structure
        run: |
          pwd
          ls -l # List files to ensure we are in the right directory
          if [ -f "./mvnw" ]; then
            ./mvnw clean package -DskipTests
          else
            echo "mvnw file not found in the consumer directory."
            exit 1
          fi

      # Build Docker image for consumer app
      - name: Build Docker image for consumer app
        run: |
          pwd
          ls -R # List directory structure to ensure consumer directory exists
          docker build -t ghcr.io/pravesh-77/consumer-app:latest ./assesment/consumer
          echo "${{ secrets.KAFKA_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/pravesh-77/consumer-app:latest

      # Build and package producer app
      - name: Build and package producer app
        working-directory: ./assesment/producer  # Update the path based on the actual repo structure
        run: |
          pwd
          ls -l # List files to ensure we are in the right directory
          if [ -f "./mvnw" ]; then
            ./mvnw clean package -DskipTests
          else
            echo "mvnw file not found in the producer directory."
            exit 1
          fi

      # Build Docker image for producer app
      - name: Build Docker image for producer app
        run: |
          pwd
          ls -R # List directory structure to ensure producer directory exists
          docker build -t ghcr.io/pravesh-77/producer-app:latest ./assesment/producer
          echo "${{ secrets.KAFKA_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/pravesh-77/producer-app:latest
